# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
   - name: WhitespaceTokenizer
   - name: RegexFeaturizer
   - name: RegexEntityExtractor
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: "DucklingEntityExtractor"
     # url of the running duckling server
     url: "http://localhost:8000"
     # dimensions to extract
     dimensions: [ "time", "email" ]
     # allows you to configure the locale, by default the language is
     # used
     locale: "NL_Nothing"
     # if not set the default timezone of Duckling is going to be used
     # needed to calculate dates from relative expressions like "tomorrow"
     timezone: "Asia/KualaLumpur"
      # docker run -p 8000:8000 rasa/duckling
   - name: DIETClassifier
     epochs: 300
     constrain_similarities: true
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 200
     retrieval_intent: faq
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 200
     retrieval_intent: chitchat
   - name: ResponseSelector
     epochs: 200
     retrieval_intent: out_of_scope
#     constrain_similarities: true
   - name: FallbackClassifier
     threshold: 0.45
     ambiguity_threshold: 0.2

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # See https://rasa.com/docs/rasa/policies for more information.
   - name: MemoizationPolicy
   - name: RulePolicy
     # Confidence threshold for the `core_fallback_action_name` to apply.
     # The action will apply if no other action was predicted with
     # a confidence >= core_fallback_threshold
     core_fallback_threshold: 0.38
     core_fallback_action_name: "utter_default"
     enable_fallback_prediction: True
   - name: TEDPolicy
     max_history: 4
     epochs: 300
     constrain_similarities: true

